import AVFoundation
import Foundation
import Speech

/// What Live can and cannot do right now, checked rather than assumed.
///
/// It replaces the flat "Connection to AI service required" state with the distinctions that
/// actually matter, because they have different fixes and different consequences:
///
/// - **Listening and generation are independent.** The microphone can work perfectly while the
///   backend is unreachable, and that is a useful session: speech is transcribed, questions are
///   detected, and only Generate is unavailable. Refusing to start at all would throw away the half
///   that works.
/// - A *client* authentication failure (the app's bearer token) is never reported as a *provider*
///   credential problem. They are different secrets held by different parties.
struct LiveReadiness: Equatable, Sendable {
    enum Blocker: Equatable, Sendable {
        case microphoneDenied
        case speechRecognitionDenied
        case speechModelUnavailable(locale: String)
        case backendNotConfigured(reason: String)
        case backendUnreachable(detail: String)
        case backendTimedOut
        case backendHostNotFound
        case transportSecurityFailed
        case deviceOffline
        case clientAuthenticationFailed
        case providerNotConfigured
        case developmentFakeEnabled

        /// Said in the words a person can act on, without naming a secret.
        var message: String {
            switch self {
            case .microphoneDenied:
                "Microphone access is denied — enable it in Settings"
            case .speechRecognitionDenied:
                "Speech recognition access is denied — enable it in Settings"
            case .speechModelUnavailable(let locale):
                "No on-device speech model for \(locale). Live will not transcribe in this language"
            case .backendNotConfigured(let reason):
                reason
            case .backendUnreachable(let detail):
                "The backend did not answer (\(detail)) — check it is running and reachable from this device"
            case .backendTimedOut:
                "The backend did not answer in time. It may be starting up — tap Retry"
            case .backendHostNotFound:
                "That backend address could not be found. If the tunnel restarted, its URL has changed"
            case .transportSecurityFailed:
                "The secure connection to the backend failed"
            case .deviceOffline:
                "This iPhone has no network connection"
            case .clientAuthenticationFailed:
                "The backend rejected this app's access token — set a token that matches COINTERVIEW_TOKENS"
            case .providerNotConfigured:
                "The backend is running but has no provider credential — answers are unavailable"
            case .developmentFakeEnabled:
                "The development fake provider is on — answers will be canned and labelled"
            }
        }

        /// Whether this stops speech being transcribed at all, as opposed to stopping answers.
        var stopsListening: Bool {
            switch self {
            case .microphoneDenied, .speechRecognitionDenied, .speechModelUnavailable:
                true
            default:
                false
            }
        }

        /// Whether trying again could plausibly succeed without the user changing anything.
        /// A timeout or a cold tunnel is worth retrying; a denied microphone is not.
        var isWorthRetrying: Bool {
            switch self {
            case .backendTimedOut, .backendUnreachable, .deviceOffline, .backendHostNotFound:
                true
            default:
                false
            }
        }
    }

    var blockers: [Blocker] = []
    /// What the backend says it is configured with, when it answered. Never contains a credential.
    var backendSummary: String?
    /// Whether the configured answer model accepts image input, as reported by the backend's
    /// verified registry. False until the backend actually says otherwise.
    var answerAcceptsImages = false
    var isChecking = false

    /// Speech can be captured and transcribed.
    var canListen: Bool { !blockers.contains { $0.stopsListening } }
    /// An answer can actually be generated by a real provider.
    var canGenerate: Bool { blockers.isEmpty }
    /// The honest middle state: a useful session with one half unavailable.
    var isListenOnly: Bool { canListen && !canGenerate }

    /// True when the failure is transient enough that Retry is the right offer.
    var isRetryable: Bool { blockers.contains { $0.isWorthRetrying } }

    /// One line for the start screen.
    var summary: String {
        if isChecking { return "Checking…" }
        if canGenerate { return "Ready · \(backendSummary ?? "backend configured")" }
        if let first = blockers.first { return first.message }
        return "Ready"
    }

    /// Permissions are requested, not assumed. Returns what the user actually granted.
    static func requestPermissions() async -> (microphone: Bool, speech: Bool) {
        let microphone = await AVAudioApplication.requestRecordPermission()
        let speech = await withCheckedContinuation { continuation in
            SFSpeechRecognizer.requestAuthorization { status in
                continuation.resume(returning: status == .authorized)
            }
        }
        return (microphone, speech)
    }

    /// Everything that can be checked without opening the microphone or spending a token.
    static func check(
        configuration: ProviderConfiguration,
        language: InterviewLanguage,
        microphonePermission: AVAudioApplication.recordPermission = AVAudioApplication.shared.recordPermission,
        speechAuthorization: SFSpeechRecognizerAuthorizationStatus = SFSpeechRecognizer.authorizationStatus(),
        probe: (ProviderConfiguration) async -> BackendProbe = LiveReadiness.probeBackend
    ) async -> LiveReadiness {
        var readiness = LiveReadiness()

        if microphonePermission == .denied { readiness.blockers.append(.microphoneDenied) }
        if speechAuthorization == .denied || speechAuthorization == .restricted {
            readiness.blockers.append(.speechRecognitionDenied)
        }

        // On-device recognition is a per-locale capability, not a global one. If the model for the
        // chosen language is missing, say so instead of silently transcribing nothing — and never
        // substitute a cloud transcriber for it.
        let locale = language.readingLanguage.requestedLocale
        if SFSpeechRecognizer(locale: locale)?.isAvailable != true {
            readiness.blockers.append(.speechModelUnavailable(locale: locale.identifier))
        }

        switch configuration.availability {
        case .unavailable(let reason):
            readiness.blockers.append(.backendNotConfigured(reason: reason))
        case .developmentFake:
            readiness.blockers.append(.developmentFakeEnabled)
        case .backend:
            switch await probe(configuration) {
            case .ok(let summary, let providerConfigured, let acceptsImages):
                readiness.backendSummary = summary
                readiness.answerAcceptsImages = acceptsImages
                if !providerConfigured { readiness.blockers.append(.providerNotConfigured) }
            case .unauthorized:
                readiness.blockers.append(.clientAuthenticationFailed)
            case .providerUnconfigured:
                readiness.blockers.append(.providerNotConfigured)
            case .timedOut:
                readiness.blockers.append(.backendTimedOut)
            case .hostNotFound:
                readiness.blockers.append(.backendHostNotFound)
            case .transportSecurityFailed:
                readiness.blockers.append(.transportSecurityFailed)
            case .offline:
                readiness.blockers.append(.deviceOffline)
            case .unreachable(let detail):
                readiness.blockers.append(.backendUnreachable(detail: detail))
            }
        }
        return readiness
    }

    enum BackendProbe: Equatable, Sendable {
        case ok(summary: String, providerConfigured: Bool, acceptsImages: Bool)
        case unauthorized
        case providerUnconfigured
        case timedOut
        case hostNotFound
        case transportSecurityFailed
        case offline
        case unreachable(detail: String)
    }

    /// Asks the backend what it is configured with, **as the app**.
    ///
    /// It probes `/v1/copilot/config`, not `/health`, for one reason: `/health` is deliberately
    /// unauthenticated, so it answers 200 even when the app's token is wrong. Probing it therefore
    /// could not tell a working setup from a rejected one, and a bad token surfaced later as a
    /// failed generation instead of an honest "the backend rejected this app's token".
    ///
    /// The timeout is deliberately generous. The original five seconds was shorter than a cold
    /// tunnel's first TLS handshake over mobile, so one slow start marked an entirely healthy
    /// backend unreachable for the rest of the session.
    static func probeBackend(_ configuration: ProviderConfiguration) async -> BackendProbe {
        guard case .backend(let url) = configuration.availability else {
            return .unreachable(detail: "no backend configured")
        }
        var request = URLRequest(url: url.appending(path: "v1/copilot/config"))
        request.timeoutInterval = probeTimeout
        request.setValue("Bearer \(configuration.token)", forHTTPHeaderField: "Authorization")
        do {
            let (data, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse else {
                return .unreachable(detail: "unexpected response")
            }
            switch http.statusCode {
            case 200:
                let configured = try JSONDecoder().decode(CopilotBackendConfiguration.self, from: data)
                return .ok(
                    summary: configured.summary,
                    providerConfigured: configured.provider_configured,
                    acceptsImages: configured.answer_accepts_images
                )
            case 401, 403:
                return .unauthorized
            case 503:
                return .providerUnconfigured
            default:
                return .unreachable(detail: "HTTP \(http.statusCode)")
            }
        } catch let error as URLError {
            // Each of these has a different fix, so each gets its own answer rather than one
            // catch-all "not reachable".
            switch error.code {
            case .timedOut: return .timedOut
            case .cannotFindHost, .cannotConnectToHost, .dnsLookupFailed: return .hostNotFound
            case .secureConnectionFailed, .serverCertificateUntrusted,
                 .serverCertificateHasBadDate, .serverCertificateNotYetValid,
                 .serverCertificateHasUnknownRoot: return .transportSecurityFailed
            case .notConnectedToInternet, .networkConnectionLost: return .offline
            default: return .unreachable(detail: error.localizedDescription)
            }
        } catch {
            return .unreachable(detail: (error as NSError).localizedDescription)
        }
    }

    /// Long enough for a cold tunnel's first handshake on a mobile connection.
    static let probeTimeout: TimeInterval = 12
}
